### ISSUE TITLE
McNearney Lake

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#12]
Here we have 3 cores from the same lake. All have (extremely certain, based on Binford) Lead-210 dates. Right now we have our pre-sett date set to 99 YBP (1851), but this site is in the Sault Ste. Marie State Forest. I looked up the associated pub, and two out of the three pre-sett samples we have assigned are at the same depth as in the pub (we've assigned a deeper pre-sett sample for the third). 

The pubs suggest that logging which resulted in an ambrosia cultivation occurred between 1899-1904. 

I'm going to update our pre-sett age to be 1890. Objections or alternative suggestions? Right now our pre-sett age is definitely too old if we assume the lead dates are certain.

**Comment by SimonGoring** [comment]
I think this is a good call.  1899 seems reasonable that far north.

**Comment by SimonGoring** [comment]
Same Lake Mary stuff:

https://github.com/PalEON-Project/stepps-baconizing/blob/master/R/utils/write_agefile_stepps.r#L210
