### ISSUE TITLE
Bacon halts when thickness too large

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#13]
I just wanted to make a note of this, because we should fix it in the future. If the thickness is too large, then Bacon throws the following (uninformative) error:

`Error in read.table(paste(set$prefix, ".out", sep = "")) : 
  no lines available in input`

To get it to run, just decrease the thickness...

**Comment by SimonGoring** [comment]
I'm going to close this issue.  I think we're past it now in this project.
