### ISSUE TITLE
210Pb email.

### ISSUE THREAD

**Issue by SimonGoring** [PalEON-Project/stepps-baconizing#16]
Send an email (@SimonGoring) to the team about the lead 210 issue, precision vs accuracy and model problems.  Figure out which plot/model might be good to highlight this issue @andydawson

**Comment by SimonGoring** [comment]
Hi all, I just wanted to share a quick update on an issue we've been having with "Baconizing".  For a number of cores we had agreed to implement a system where <sup>210</sup>Pb age error (which was not always available in neotoma) increased with depth in a regular and linear method.

From Jack:

> Lead 210 first:  I dug up an early reference  on lead 210 dating uncertainties by Binford (1990) attached and he states:  "Ninety-five per cent confidence intervals range from about 1-2 years at 10 years of age, 10-20 at 100 years, and 8-90 at 150 years old."  (Lead-210 can't be used for sediments older to 150 years old.)

This caused some issues for Bacon because often times <sup>210</sup>Pb dates are very close within the stratigraphy to an identified pre-settlement samples, and Bacon looks at the two uncertainties (for example +1SD of 3yrs for the <sup>210</sup>Pb and 50 for the pre-sett at [Andrus Lake](https://github.com/PalEON-Project/stepps-baconizing/blob/master/Cores/ANDRUSLK/ANDRUSLK.csv)) and chokes.

I've emailled Mark Brenner to ask him about it, he was very clear that the errors reported are precision errors for the counts and not accuracy ages for the actual age of the sediment, which implies that they don't account for things like mixing within the stratigraphy.  William Kenny, who was (is?) Mark's lab tech says he has a paper in prep that identifies systematic error in older accumulation rates (<1930) calculated from the Constant Rate of Supply model.  He didn't indicate what that error was, but said he'd pass along the paper following a move.

So, thoughts?  Should we loosen the <sup>210</sup>Pb uncertainty estimates to align more closely with the pre-settlement error estimate?
@IceAgeEcologist @paciorek @andydawson

**Comment by SimonGoring** [comment]
@andydawson where in the code do you assign the errors to the <sup>210</sup>Pb dates?

**Comment by andydawson** [comment]
In `write_agefile_stepps.r`, I call `set_lead_error()`, which is defined in `helpers.r`.

**Comment by andydawson** [comment]
Just following up - our upper midwest prediction data set has 12 lead-210 cores. Details are below. max_age is the maximum lead-210 age. All of them have a presettlement sample, so we can still fit an age-depth model using the core top and the pre-set sample (as we do for many other cores). I do think we lose information by fitting a linear model, but Bacon has a tough time with dates that are so certain. Either way, we get an age-depth model that isn't perfect, but for different reasons...

I do think that it is best to leave them out for now, unless someone has a strategic way to deal with this.

```
       site siteid max_age presett
1  ANDRUSLK     81      99    TRUE
2   BROWNLK    129      80    TRUE
3  BROWNSBY    132     158    TRUE
4  CAMP12LK    135      66    TRUE
5  DENTONLK    167      65    TRUE
6  DUNNIGAN    171      85    TRUE
7   HUSTLER     14      61    TRUE
8  MCNRNY2A     65      87    TRUE
9  MCNRNY3A    143      87    TRUE
10 MCNRNY4A    144      88    TRUE
11   NELSLK     72      66    TRUE
12  OTTOMLK     75      79    TRUE
```

**Comment by SimonGoring** [comment]
Any follow-up on this @andydawson?  I think the outcome was the assignment of errors we report in the new paper text, right?

**Comment by SimonGoring** [comment]
@andydawson can you close this issue with an explanation?

**Comment by SimonGoring** [comment]
These uncertainties are assigned in `lead_error_paleon.R`, in the `R/helpers` directory:

https://github.com/PalEON-Project/stepps-baconizing/blob/master/R/utils/helpers.r#L43
