### ISSUE TITLE
Wolsfeld Lake (dataset ID 3031)

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#18]
When I get the chron control table for Wolsfeld Lake using

`get_chroncontrol(5371)`,

I get a list where the `chron.control` object contains entries that are of the type

`Interpolated, corrected for compaction`

@SimonGoring : what is this, and does it belong in the control table?

**Comment by SimonGoring** [comment]
Because of re-jigging of the `get_chroncontrol` function this should work as:

```r
get_dataset(3031) %>% get_chroncontrol
```

From the paper:

> Because water content in the topmost sediments of Wolsfeld Lake rapidly decreases with depth, deposition time above the Ambrosia-rise was corrected for compaction (loss of water from the sediment). In general, this correction requires the assumptions that influx of sediment was constant and that the sediments have uniform compaction characteristics. Neither of these assumptions is likely. Therefore, the correction for compaction was based on just the organic fraction of total bulk density, because the influx of this fraction varies less than the inorganic fraction in the core and because the organic bulk density is virtually constant with depth. 

[Grimm, 1983](http://onlinelibrary.wiley.com/doi/10.1111/j.1469-8137.1983.tb03434.x/pdf)
