### ISSUE TITLE
Ondris Pont (dataset ID 1831)

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#19]
Chronology in sample.meta is not the default chronology. Make sure the reservoir corrected RC dates are used!

**Comment by SimonGoring** [comment]
This the the case generally right?  If I fix it in `neotoma` is that going to screw up the code for the records here?

**Comment by SimonGoring** [comment]
Noted elsewhere.  This is a problem with the Neotoma API.
