### ISSUE TITLE
Fix Bacon code - plotting.

### ISSUE THREAD

**Issue by SimonGoring** [PalEON-Project/stepps-baconizing#2]
Fix the Bacon plotting limits (yes I did this once, but they are still not quite right).

**Comment by SimonGoring** [comment]
I don't know what this is about., I'm clearly no writing helpful issues.  I'm closing it.

**Comment by andydawson** [comment]
This is because the plotting limits in Bacon are sometime incorrect, and RC dates are not within limits. This should be fixed, but maybe not now or here. What do you think?
