### ISSUE TITLE
Create trimmed Cores folder

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#24]
Currently the Cores folder is ~5GB, which is too big to add to the git repo. Plan is to make a trimmed version including only the minimum contents which include the bacon output for the chosen thickness, the bchron output, and maybe the original data file for the core with the chron controls.

**Comment by SimonGoring** [comment]
This was done, but I couldn't find the right commit.  @andydawson I'm closing this, but if you know which commit this is linked to, could you add it in & close the issue again?
