### ISSUE TITLE
Get a summary of the section widths used in the models.

### ISSUE THREAD

**Issue by SimonGoring** [PalEON-Project/stepps-baconizing#25]
For the Results section it would be good to show a table of section width selections, maybe as a function of total core depth (of it varies).

Can you pull this out @andydawson?  Or if you get the zip working maybe I can figure it out from the outputs.

**Comment by andydawson** [comment]
Yes, I can do this. Maybe this should be in a table with all the meta data? Like dataset name, id, thickness, etc.? Anything else you would like in the table? Other possibilities are lat, long, min and max geochron ages, settlement horizon indicator...

**Comment by SimonGoring** [comment]
This is done now and incorporated in the paper and in the file `R/thick_model.R`
