### ISSUE TITLE
Lead-210 error uncertainty

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#28]
Estimate lead-210 error uncertainties based on gam model using lead-210 dates that have recorded uncertainties. Then run bacon models. Compare the width of the posteriors for age estimates for the estimated and recorded lead-210 dates. This will allow us to begin to think about if the lead-210 error estimates we assigned are biased.

**Comment by SimonGoring** [comment]
This is now done and incorporated in the so-called Binford plot.
