### ISSUE TITLE
Green Lake

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#4]
From Eric:
"According to Lawrenz (1975) p. 6: “Upon extrusion the top 10 cm of sediment collapsed and were discarded.” The top pollen sample at 10 cm is seemingly below the European settlement horizon. The COHMAP chronology made a guess of 200 yrs for the 10 cm depth. For a new age model, I’d probably assign the year of coring (-22 yr BP) to 0 cm, but then check that the resultant age at 10 cm is reasonably below the time of European settlement. If not, you may have to do what COHMAP did. The top sample of this site is not designated as a modern sample in Neotoma."

So we wrongly assigned a pre-sett sample. To run Bacon, I am adding the core top constraint as suggested by Eric.

Dataset ID 982.

**Comment by andydawson** [comment]
Fit still doesn't look good. Noticed that the last two (of three) RC dates are labelled as reservoir corrected, but the first is not. Notes on NAPD say that was done to 'fit Demont and Vestaburg'. Not sure what that means, and I do not have access to the pub. True reservoir correction?

**Comment by SimonGoring** [comment]
I think this means that the basal date at [Green Lake](http://apps.neotomadb.org/explorer/?datasetid=982) is too old compared to [Vestaburg](http://apps.neotomadb.org/explorer/?datasetid=3831) & [Demont](http://apps.neotomadb.org/explorer/?datasetid=679).  So they adjuted the record to get a coherent basal date across the records, assuming:
1. That Green Lake had some sort of hard water effect (that only affected the lower dates) and,
2. The deglaciation was somewhat consistent across the region.

All three of these records come from theses or are (apparently) unpublished, so it's a bit tricky to figure out.  I think we accept that this decision was appropriate.
