### ISSUE TITLE
Comparing errors at pre-settlement samples

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#42]
Need Bacon estimated ages, our assigned ages, and the default age/depth from Neotoma. Only for sites with expert elicitation.

Make a table
site, depth, age, pre-sett source, age-source, depth-source, uncertainty

**Comment by SimonGoring** [comment]
This is now resolved as of commit 087b362.  I made plots and added text to the results.  All analysis is in the file [`R/elicitation_plot.R`](https://github.com/PalEON-Project/stepps-baconizing/blob/master/R/elicitation_plot.R).
