### ISSUE TITLE
Chippewa Bog (dataset ID 369)

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#5]
No core top! 

Wrongly assigned a pre-settlement sample. Remove from calibration data set, and do NOT add pre-sett sample when building prediction data set.

**Comment by SimonGoring** [comment]
Is this resolved properly at this point @andydawson?  Should we add a file that is a csv (or table of some sort) with:

| Name | DatasetID | Reason |
| --- | --- | --- |
| xxx | 123 | So bad. |

Something?

**Comment by SimonGoring** [comment]
This is now resolved, in a huge and messy list of exceptions that could use some cleaning, starting around:

https://github.com/PalEON-Project/stepps-baconizing/blob/master/R/utils/write_agefile_stepps.r#L207
