### ISSUE TITLE
Wolverine Lake (dataset ID 3032)

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#6]
From Eric:

The metadata for this site should be updated. Futyma apparently provided these data to COHMAP before he completed his dissertation, which has this site. The notes for the COHMAP age model say there isn’t an Ambrosia rise, but there is. The upper 100 cm was taken with a frozen finger,  only the top 24 cm were retrieved. According to Futyma’s (1982) thesis, p, 34: “The frozen core segment was dated using pollen stratigraphic changes related to European settlement of the region, mainly the rise in Ambrosia. A date of 1880 A.D. is estimated for the 10-cm level and 1980 A.D. for the very top of the core.” That should be what you need for a new age model! The top sample is designated as modern, and it should be.

So, we are going to keep our pre-sett sample, but re-assign the core top age to -30 at a depth of 0.

**Comment by SimonGoring** [comment]
This is addressed now in the `utils` folder:

https://github.com/PalEON-Project/stepps-baconizing/blob/master/R/utils/write_agefile_stepps.r#L178
