### ISSUE TITLE
Kotiranta (dataset ID 1548)

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#7]
From Eric:

The top sample below the Ambrosia rise. From p. 48 in Wright & Watts (1969): “Although the Kotiranta, Glatsch, and Rossburg diagrams do not reach close enough to the surface to record the changes related to disturbance, the Weber Lake diagrams show the usual rise in Ambrosia and chenopods at all three coring sites-the lake center, the edge of the fringing bog, and the center of the bog.” So the top date is a guess, and the top sample should not have designated as a modern sample. I’ll fix that.

So no actual core top, so do not assign pre-sett. Top age is a guess - should we include it? Leaving it in for now until we decide otherwise.

**Comment by SimonGoring** [comment]
Dealt with in the same place as Chippewa, but we leave the top date, but don't assign a presettlement date.

https://github.com/PalEON-Project/stepps-baconizing/blob/master/R/utils/write_agefile_stepps.r#L207
