### ISSUE TITLE
Lake Mary (dataset ID 3473)

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#8]
From Eric:
I checked both Tom Webb’s thesis and the American Midland Naturalist paper, and there’s no discussion of the top age. However, there is no Ambrosia rise, which suggests that the top sediments are missing. They apparently did not take a separate surface core as we do now, so this isn’t too surprising. COHMAP assigned an age of 200 BP to the top sample, so this implies that they also believed the top sediment was missing. As this was Tom Webb’s site, the COHMAP assignment would also represent the author’s thinking. Thus, this age is a reasonable guesstimate of the top age.

Despite age assignment of 200 BP to the surface sample, it was still regarded as a “surface sample” by COHMAP. As the vegetation in northern Wisconsin is not as dramatically altered as in some other areas, this probably isn’t terribly unreasonable, especially for the kinds of synoptic studies COHMAP was doing. However, I would keyword this sample a “pre-European settlement” sample rather than a “modern surface sample.” 

The plan:
We are going to discard our pre-sett sample. The top sample is a guess, but for now I'm leaving it in as is.

**Comment by SimonGoring** [comment]
Same block as Chippewa and Kotiranta:

https://github.com/PalEON-Project/stepps-baconizing/blob/master/R/utils/write_agefile_stepps.r#L210
