### ISSUE TITLE
Overconfident Lead-210 dates?

### ISSUE THREAD

**Issue by andydawson** [PalEON-Project/stepps-baconizing#9]
We were going to look into this - the way we are assigning error know means that we are quite certain. For example, with Andrus Lake, all our lead-210 errors are set to 1 sd (these are actually rounded up because if I recall correctly Bacon didn't like non-integer errors). This contrasts to our pre-sett error, which is set to 50. Quite a difference...

I've done some looking but haven't found much research that looks at lead dating uncertainty. Some articles say not to use it at all because of mixing in the upper sediments, and should always be used in combination with another trace marker. 

I don't know enough about lead dating to come up with a solution, but being able to date 50 year old sediment within a year of the actual date seems somewhat unrealistic. 

Thoughts?

I know Steve suggested we consult Mark Brenner (UFl) and Dan Engstrom. Perhaps we should send an email to touch base? @SimonGoring do you know these guys at all?

**Comment by SimonGoring** [comment]
I'm going to email Mark Brenner.  I don't know him, but this is something
I've been wondering about for a while, so maybe he can help.

**Comment by SimonGoring** [comment]
I've moved on to issue #16.  I'm going to close this issue, but leave this response from Mark Brenner:

> Hi Simon – I include Dr. William Kenney on my reply because he is the master of our gamma counting facility and can tell you what is available from our archives.  I attach the 1990 paper by Mike Binford, which is often cited for uncertainty analysis.  The uncertainty generally increases downcore, in large part because the number of counts decreases in the older sediments.  Re your last paragraph below, the uncertainty says nothing about what happened to the sediment before activity measurement – that is, it does not assess whether things were mixed.  The uncertainty, as Binford reports it, is a function of the counts, and that is why the errors grow with age.  And it explains why near the surface, errors are small.  Assessing other types of error is difficult.  Maybe the way to think about this is that this error analysis gets at precision, but you seem to be worried about accuracy.  Hope that helps. Best - mark
